/**
 * Seed script — 10 Magic + 10 Pokémon sample cards.
 * Run: npm run seed
 */
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

const magicCards = [
  {
    tcg: 'magic',
    external_id: 'b0faa7f2-b547-42c4-a810-839da50dadfe',
    name: 'Black Lotus',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '232',
    rarity: 'rare',
    image_url: 'https://cards.scryfall.io/large/front/b/0/b0faa7f2-b547-42c4-a810-839da50dadfe.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/b/0/b0faa7f2-b547-42c4-a810-839da50dadfe.jpg',
    colors: [],
    mana_cost: '{0}',
    cmc: 0,
    oracle_text: '{T}, Sacrifice Black Lotus: Add three mana of any one color.',
    market_price_eur: 230000.00,
  },
  {
    tcg: 'magic',
    external_id: 'e9d5aee0-5963-41db-a22b-cfea40a967a3',
    name: 'Mox Sapphire',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '265',
    rarity: 'rare',
    image_url: 'https://cards.scryfall.io/large/front/e/9/e9d5aee0-5963-41db-a22b-cfea40a967a3.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/e/9/e9d5aee0-5963-41db-a22b-cfea40a967a3.jpg',
    colors: ['U'],
    mana_cost: '{0}',
    cmc: 0,
    oracle_text: '{T}: Add {U}.',
    market_price_eur: 25760.00,
  },
  {
    tcg: 'magic',
    external_id: '9ea8179a-d3c9-4cdc-a5a6-9afa6c83a4ff',
    name: 'Ancestral Recall',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '47',
    rarity: 'rare',
    image_url: 'https://cards.scryfall.io/large/front/9/e/9ea8179a-d3c9-4cdc-a5a6-9afa6c83a4ff.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/9/e/9ea8179a-d3c9-4cdc-a5a6-9afa6c83a4ff.jpg',
    colors: ['U'],
    mana_cost: '{U}',
    cmc: 1,
    oracle_text: 'Target player draws three cards.',
    market_price_eur: 12880.00,
  },
  {
    tcg: 'magic',
    external_id: 'fc46a4b5-a897-4a42-b8b7-d622374fdc41',
    name: 'Lightning Bolt',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '161',
    rarity: 'common',
    image_url: 'https://cards.scryfall.io/large/front/f/c/fc46a4b5-a897-4a42-b8b7-d622374fdc41.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/f/c/fc46a4b5-a897-4a42-b8b7-d622374fdc41.jpg',
    colors: ['R'],
    mana_cost: '{R}',
    cmc: 1,
    oracle_text: 'Lightning Bolt deals 3 damage to any target.',
    market_price_eur: 2.30,
  },
  {
    tcg: 'magic',
    external_id: 'fd12c1d3-7f71-4c56-b66e-ebec5d55c3a3',
    name: 'Counterspell',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '54',
    rarity: 'common',
    image_url: 'https://cards.scryfall.io/large/front/f/d/fd12c1d3-7f71-4c56-b66e-ebec5d55c3a3.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/f/d/fd12c1d3-7f71-4c56-b66e-ebec5d55c3a3.jpg',
    colors: ['U'],
    mana_cost: '{U}{U}',
    cmc: 2,
    oracle_text: 'Counter target spell.',
    market_price_eur: 1.10,
  },
  {
    tcg: 'magic',
    external_id: '2fab0ea3-0688-4291-a185-9e8a8b7c2fdb',
    name: 'Dark Ritual',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '94',
    rarity: 'common',
    image_url: 'https://cards.scryfall.io/large/front/2/f/2fab0ea3-0688-4291-a185-9e8a8b7c2fdb.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/2/f/2fab0ea3-0688-4291-a185-9e8a8b7c2fdb.jpg',
    colors: ['B'],
    mana_cost: '{B}',
    cmc: 1,
    oracle_text: 'Add {B}{B}{B}.',
    market_price_eur: 3.20,
  },
  {
    tcg: 'magic',
    external_id: '0217de58-7585-41db-86de-e56b0e1f5cb2',
    name: 'Shivan Dragon',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '175',
    rarity: 'rare',
    image_url: 'https://cards.scryfall.io/large/front/0/2/0217de58-7585-41db-86de-e56b0e1f5cb2.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/0/2/0217de58-7585-41db-86de-e56b0e1f5cb2.jpg',
    colors: ['R'],
    mana_cost: '{4}{R}{R}',
    cmc: 6,
    oracle_text: 'Flying. {R}: Shivan Dragon gets +1/+0 until end of turn.',
    power: '5',
    toughness: '5',
    market_price_eur: 41.40,
  },
  {
    tcg: 'magic',
    external_id: 'ea16e2e7-1e25-4fb9-8e4a-5e3db0f3ceab',
    name: 'Serra Angel',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '26',
    rarity: 'uncommon',
    image_url: 'https://cards.scryfall.io/large/front/e/a/ea16e2e7-1e25-4fb9-8e4a-5e3db0f3ceab.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/e/a/ea16e2e7-1e25-4fb9-8e4a-5e3db0f3ceab.jpg',
    colors: ['W'],
    mana_cost: '{3}{W}{W}',
    cmc: 5,
    oracle_text: 'Flying, vigilance.',
    power: '4',
    toughness: '4',
    market_price_eur: 23.00,
  },
  {
    tcg: 'magic',
    external_id: 'a9f33584-6de0-4d37-b9be-81cf6c9ee3ef',
    name: 'Llanowar Elves',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '181',
    rarity: 'common',
    image_url: 'https://cards.scryfall.io/large/front/a/9/a9f33584-6de0-4d37-b9be-81cf6c9ee3ef.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/a/9/a9f33584-6de0-4d37-b9be-81cf6c9ee3ef.jpg',
    colors: ['G'],
    mana_cost: '{G}',
    cmc: 1,
    oracle_text: '{T}: Add {G}.',
    power: '1',
    toughness: '1',
    market_price_eur: 1.66,
  },
  {
    tcg: 'magic',
    external_id: '7f2a0e89-b0e4-4c3a-b4a2-8f6e5c2d1a0b',
    name: 'Wrath of God',
    set_name: 'Limited Edition Alpha',
    set_code: 'lea',
    collector_number: '37',
    rarity: 'rare',
    image_url: 'https://cards.scryfall.io/large/front/7/f/7f2a0e89-b0e4-4c3a-b4a2-8f6e5c2d1a0b.jpg',
    image_thumbnail_url: 'https://cards.scryfall.io/small/front/7/f/7f2a0e89-b0e4-4c3a-b4a2-8f6e5c2d1a0b.jpg',
    colors: ['W'],
    mana_cost: '{2}{W}{W}',
    cmc: 4,
    oracle_text: "Destroy all creatures. They can't be regenerated.",
    market_price_eur: 7.82,
  },
];

const pokemonCards = [
  {
    tcg: 'pokemon',
    external_id: 'base1-4',
    name: 'Charizard',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '4',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/4_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/4.png',
    colors: ['Fire'],
    hp: 120,
    stage: 'Stage 2',
    market_price_eur: 322.00,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-2',
    name: 'Blastoise',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '2',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/2_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/2.png',
    colors: ['Water'],
    hp: 100,
    stage: 'Stage 2',
    market_price_eur: 165.60,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-15',
    name: 'Venusaur',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '15',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/15_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/15.png',
    colors: ['Grass'],
    hp: 100,
    stage: 'Stage 2',
    market_price_eur: 147.20,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-58',
    name: 'Pikachu',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '58',
    rarity: 'Common',
    image_url: 'https://images.pokemontcg.io/base1/58_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/58.png',
    colors: ['Lightning'],
    hp: 40,
    stage: 'Basic',
    market_price_eur: 16.56,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-10',
    name: 'Mewtwo',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '10',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/10_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/10.png',
    colors: ['Psychic'],
    hp: 60,
    stage: 'Basic',
    market_price_eur: 110.40,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-13',
    name: 'Chansey',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '13',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/13_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/13.png',
    colors: ['Colorless'],
    hp: 120,
    stage: 'Basic',
    market_price_eur: 50.60,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-5',
    name: 'Clefairy',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '5',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/5_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/5.png',
    colors: ['Colorless'],
    hp: 40,
    stage: 'Basic',
    market_price_eur: 36.80,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-6',
    name: 'Gyarados',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '6',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/6_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/6.png',
    colors: ['Water'],
    hp: 130,
    stage: 'Basic',
    market_price_eur: 59.80,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-9',
    name: 'Magneton',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '9',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/9_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/9.png',
    colors: ['Lightning'],
    hp: 60,
    stage: 'Stage 1',
    market_price_eur: 34.96,
  },
  {
    tcg: 'pokemon',
    external_id: 'base1-12',
    name: 'Ninetales',
    set_name: 'Base Set',
    set_code: 'base1',
    collector_number: '12',
    rarity: 'Rare Holo',
    image_url: 'https://images.pokemontcg.io/base1/12_hires.png',
    image_thumbnail_url: 'https://images.pokemontcg.io/base1/12.png',
    colors: ['Fire'],
    hp: 80,
    stage: 'Stage 1',
    market_price_eur: 44.16,
  },
];

async function seed() {
  console.log('Seeding cards...');

  const { data, error } = await supabase
    .from('cards')
    .upsert([...magicCards, ...pokemonCards], {
      onConflict: 'tcg,external_id',
      ignoreDuplicates: false,
    })
    .select('id, name, tcg');

  if (error) {
    console.error('Seed failed:', error.message);
    process.exit(1);
  }

  console.log(`Seeded ${data.length} cards (${magicCards.length} Magic, ${pokemonCards.length} Pokémon).`);
}

seed();
